/*-------------------------------------------------------------------------
 *
 * pgxc_class_d.h
 *    Macro definitions for pgxc_class
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PGXC_CLASS_D_H
#define PGXC_CLASS_D_H

#define PgxcClassRelationId 9001

#define Anum_pgxc_class_pcrelid 1
#define Anum_pgxc_class_pclocatortype 2
#define Anum_pgxc_class_pcattnum 3
#define Anum_pgxc_class_pchashalgorithm 4
#define Anum_pgxc_class_pchashbuckets 5
#define Anum_pgxc_class_nodeoids 6

#define Natts_pgxc_class 6


#endif							/* PGXC_CLASS_D_H */
