/*-------------------------------------------------------------------------
 *
 * pgxc_node_d.h
 *    Macro definitions for pgxc_node
 *
 * Portions Copyright (c) 1996-2022, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PGXC_NODE_D_H
#define PGXC_NODE_D_H

#define PgxcNodeRelationId 9015
#define PgxcClassPgxcRelIdIndexId 9002
#define PgxcNodeOidIndexId 9010
#define PgxcNodeNodeNameIndexId 9011
#define PgxcGroupGroupNameIndexId 9012
#define PgxcGroupOidIndexId 9013
#define PgxcNodeNodeIdIndexId 9003

#define Anum_pgxc_node_oid 1
#define Anum_pgxc_node_node_name 2
#define Anum_pgxc_node_node_type 3
#define Anum_pgxc_node_node_port 4
#define Anum_pgxc_node_node_host 5
#define Anum_pgxc_node_nodeis_primary 6
#define Anum_pgxc_node_nodeis_preferred 7
#define Anum_pgxc_node_node_id 8

#define Natts_pgxc_node 8


#endif							/* PGXC_NODE_D_H */
