/*-------------------------------------------------------------------------
 *
 * pgxc_group_d.h
 *    Macro definitions for pgxc_group
 *
 * Portions Copyright (c) 1996-2022, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PGXC_GROUP_D_H
#define PGXC_GROUP_D_H

#define PgxcGroupRelationId 9014

#define Anum_pgxc_group_oid 1
#define Anum_pgxc_group_group_name 2
#define Anum_pgxc_group_group_members 3

#define Natts_pgxc_group 3


#endif							/* PGXC_GROUP_D_H */
